name: cinema_booking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  font_awesome_flutter:
  google_fonts:
  toastification: ^3.2.0
  dio:
  go_router:
  shared_preferences:
  lottie: ^3.3.3
  intl: ^0.20.2
  image_picker:
  webview_flutter: ^4.8.0
  webview_flutter_web: ^0.2.3+2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
